In [1]:
import numpy as np

# 1) HackerRank-Array

### Task

You are given a space separated list of numbers. 
Your task is to print a reversed NumPy array with the element type float.

### Input Format
A single line of input containing space separated numbers.

### Output Format
Print the reverse NumPy array with type float.

### Sample Input
1 2 3 4 -8 -10

### Sample Output
[-10.  -8.   4.   3.   2.   1.]


In [2]:
def arrays(arr):
    #reverses the list than turns into an array that is float type
    return np.array(arr[::-1], float)
    
#arr = input().strip().split(' ')
#this was in the question but I am assigning the given input to the array
arr=[1,2,3,4,-8,-10]
result = arrays(arr)
print(result)

[-10.  -8.   4.   3.   2.   1.]


In [3]:
np.zeros((2,2,5,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

# 2) HackerRank-Concatenate


### Task
You are given two integer arrays of size N x P and M x P. Your task is to concatenate the arrays along axis .

#### Input Format
The first line contains space separated integers ,  and . 
The next  lines contains the space separated elements of the  columns. 
After that, the next  lines contains the space separated elements of the  columns.

#### Output Format
Print the concatenated array of size X.

#### Sample Input
4 3 2
1 2
1 2 
1 2
1 2
3 4
3 4
3 4 

#### Sample Output
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]] 

In [ ]:
n,m,p = map(int, input().split())

#takes the inputs and puts them into the array as in format
arr1=np.array([input().split() for i in range(n)], int)
arr2=np.array([input().split() for j in range(m)], int)

#axis=0 is row based concatenate
print(np.concatenate((arr1,arr2),axis=0))


## 3) HackerRank-Min/Max Numpy

### Task
You are given a 2-D array with dimensions N X M. 
Your task is to perform the min function over axis  and then find the max of that.


### Input Format
The first line of input contains the space separated values of n and m. 
The next  lines contains  space separated integers.

### Output Format
Compute the min along axis  and then print the max of that result.

### Sample Input
4 2<br>
2 5<br>
3 7<br>
1 3<br>
4 0

### Sample Output
3

### Explanation
The min along axis 1 = [2,3,1,0]<br><br>
The max of [2,3,1,0] = 3

In [ ]:

#Takes the n x m
n,m = map(int,input().split())

#adds each element to the array
arr1=np.array([input().split() for i in range(n)], int)

#minimum value along a given axis then finds the max element
print(max(np.min(arr1, axis = 1)))

## 4) HackerRank Sum and Prod/Numpy

### Task
You are given a 2-D array with dimensions N X M. 
Your task is to perform the  tool over axis  and then find the  of that result.

### Input Format
The first line of input contains space separated values of n and m. 
The next  lines contains  space separated integers.

### Output Format
Compute the sum along axis . Then, print the product of that sum.

### Sample Input
2 2<br>
1 2<br>
3 4
### Sample Output
24

### Explanation
The sum along axis  0 = [4 6 ] <br><br>
The product of this sum = 24

In [ ]:
n,m = map(int,input().split())

arr1=np.array([input().split() for i in range(n)], int)

#got the sum then returned the product
print(np.prod(np.sum(arr1, axis = 0)))